#!/bin/sh

# CARREGA O .reshrc JURO VEY!
[ -f "$HOME/.reshrc" ] && . "$HOME/.reshrc"

while true; do
    # Prompt limpo sem o -e bugado ;-;
    printf "chronos@localhost:$(pwd)€ "
    read command

    if [ -z "$command" ]; then continue; fi
    if [ "$command" = "exit" ]; then break; fi

    # Salva no histórico manualmente kakejskksjskskdjkd
    echo "$command" >> "$HOME/.resh_history"

    # Tenta rodar o comando
    eval "$command" 2>/dev/null || echo "resh: $command: não achei ;-; JURO VEY!"
done

