#!/data/data/com.termux/files/usr/bin/bash

# CARREGA O .reshrc JURO VEY!
[ -f "$HOME/.reshrc" ] && . "$HOME/.reshrc"

# Configura o arquivo de histórico pro read -e usar kakejskksjskskdjkd
HISTFILE="$HOME/.resh_history"
history -r "$HISTFILE"

while true; do
    # O prompt mais lindo de Sorocaba JURO VEY
    # Usei o -p do read que é mais chique kakejskksjskskdjkd
    read -e -p "chronos@localhost:$(pwd | sed "s|$HOME|~|")€ " command

    # Se der Ctrl+D ou estiver vazio JURO
    if [ $? -gt 128 ]; then exit; fi
    if [ -z "$command" ]; then continue; fi
    if [ "$command" = "exit" ]; then break; fi

    # Salva no histórico do Bash e no arquivo JURO!
    history -s "$command"
    history -w "$HISTFILE"

    # Tenta rodar a magia
    eval "$command" 2>/dev/null || echo "resh: $command: não achei ;-; JURO VEY!"
done
